#!/bin/bash
#PBS -l nodes=1:ppn=16:xk
#PBS -N bluewaters_test_2
#PBS -l walltime=30:00:00
#PBS -e $PBS_JOBNAME.$PBS_JOBID.err
#PBS -o $PBS_JOBNAME.$PBS_JOBID.out
#PBS -M sahitil2@illinois.edu
cd ~/scratch/verydcn-for-text-classification/
. /opt/modules/default/init/bash
module load bwpy
module load cudatoolkit
aprun -n 1 -N 1 time python3 main.py --dataset 'ag_news' --batch_size 100 --lr 0.0001 --max_epoch 30 --depth 29 --num_classes 4 --downsample 1 
