#!/bin/bash
#PBS -l nodes=1:ppn=16:xk
#PBS -N bluewaters_test_2
#PBS -l walltime=30:00:00
#PBS -e $PBS_JOBNAME.$PBS_JOBID.err
#PBS -o $PBS_JOBNAME.$PBS_JOBID.out
#PBS -M sahitil2@illinois.edu
cd ~/scratch/verydcn-for-text-classification/
. /opt/modules/default/init/bash
module load bwpy
module load cudatoolkit
aprun -n 1 -N 1 python3 LSTMtraining.py --dataset 'amazon' --num_classes 5 --num_epochs 15
